# Combining Columns

In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('E0_.csv')
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,09/08/2019,20:00,Liverpool,Norwich,4,1,H,4,0,...,3.43,-2.25,1.91,1.99,1.94,1.98,1.99,2.07,1.90,1.99
1,E0,10/08/2019,12:30,West Ham,Man City,0,5,A,0,1,...,2.91,1.75,1.95,1.95,1.96,1.97,2.07,1.98,1.97,1.92
2,E0,10/08/2019,15:00,Bournemouth,Sheffield United,1,1,D,0,0,...,1.92,-0.50,1.95,1.95,1.98,1.95,2.00,1.96,1.96,1.92
3,E0,10/08/2019,15:00,Burnley,Southampton,3,0,H,0,0,...,1.71,0.00,1.87,2.03,1.89,2.03,1.90,2.07,1.86,2.02
4,E0,10/08/2019,15:00,Crystal Palace,Everton,0,0,D,0,0,...,1.71,0.25,1.82,2.08,1.97,1.96,2.03,2.08,1.96,1.93

In [10]:
#Gabung Nama Team
HT = df['HomeTeam']
AT = df['AwayTeam']
getHT = HT.str[0:3]
getAT = AT.str[0:3]
match = getHT + getAT
match

0      LivNor
1      WesMan
2      BouShe
3      BurSou
4      CryEve
        ...
375    LeiMan
376    ManNor
377    NewLiv
378    SouShe
379    WesAst
Length: 380, dtype: object

In [11]:
#Combine
FTHG = df['FTHG']
FTAG = df['FTAG']
HTHG = df['HTHG']
HTAG = df['HTAG']
Goal = FTHG + FTAG + HTHG + HTAG

HS = df['HS']
AS = df['AS']
Shoot = HS + AS

HST = df['HST']
AST = df['AST']
Target = HST + AST

HF = df['HF']
AF = df['AF']
Foul = HF + AF

HC = df['HC']
AC = df['AC']
Corner = HC + AC

HY = df['HY']
AY = df['AY']
Yellow = HY + AY

HR = df['HR']
AR = df['AR']
Red = HR + AR
Score = Goal + Shoot + Target + Foul + Corner + Yellow + Red

In [12]:
dff = pd.DataFrame({'Div':df.Div, 'Match': match, 'Goal': Goal, 'Shoot': Shoot, 'OnTarget': Target, 'Foul': Foul, 'Corner': Corner, 'Yellow': Yellow, 'Red': Red, 'Score': Score})

In [13]:
dff.head()

  Div   Match  Goal  Shoot  OnTarget  Foul  Corner  Yellow  Red  Score
0  E0  LivNor     9     27        12    18      13       2    0     81
1  E0  WesMan     6     19        12    19       2       4    0     62
2  E0  BouShe     2     21         6    29       7       3    0     68
3  E0  BurSou     3     21         7    18       9       0    0     58
4  E0  CryEve     0     16         5    30       8       3    1     63

In [14]:
dff.to_csv (r'football_E0.csv', index = False, header=True)

print (dff)

    Div   Match  Goal  Shoot  OnTarget  Foul  Corner  Yellow  Red  Score
0    E0  LivNor     9     27        12    18      13       2    0     81
1    E0  WesMan     6     19        12    19       2       4    0     62
2    E0  BouShe     2     21         6    29       7       3    0     68
3    E0  BurSou     3     21         7    18       9       0    0     58
4    E0  CryEve     0     16         5    30       8       3    1     63
..   ..     ...   ...    ...       ...   ...     ...     ...  ...    ...
375  E0  LeiMan     2     21         6    23       6       5    1     64
376  E0  ManNor     7     36        14    11       9       2    0     79
377  E0  NewLiv     6     17         8    16       6       1    0     54
378  E0  SouShe     5     18         7    25      10       1    0     66
379  E0  WesAst     2     23         5    29       7       3    0     69

[380 rows x 10 columns]